### PR TITLE
Propose a new xstream icon

### PR DESCRIPTION
**Pull request by versable**
The 'X' is a character from the font "operating instructions"
which uses its own license, which states:
    "The fonts are provided free for personal or commercial use,"
    "however they may not be redistributed, sold or modified without"
    "the permission of Jakob Fischer / pizzadude.dk."

### CODE REVIEW

**Comment by versable** [comment]
Resized, I will shoot the author a quick mail

**Comment by Lynx187** [comment]
Don't be in such a hurry.
..
 I think since you are just using this letter in a picture you are not redistributing the font.

**Comment by versable** [comment]
You might be right, as long as it is not a SVG with the font embedded.

**Comment by versable** [comment]
Updated the new logo: It uses the old 'X' now to avoid any copyright issues

**Pull request closed without merging**
