### PR TITLE
Add new site FilmPalast.to

### PR DESCRIPTION
**Pull request by versable**

### CODE REVIEW

**Comment by Lynx187** [comment]
Please use the requestHandler whenever it is possible, except you are sure that caching or cookie handling is not necessary or counterproductive.

PS: in the future I want to pass the parameters to the fuctions which are called via the xstream.py. Already adding this as an optional argument to the relevant functions, would be good. I'm doing this also for the other site-plugins.

**Comment by versable** [comment]
I did try the requestHandler, which did not work via 'addParameter'. urllib2 did not work either. I guess we could expand requestHandler to use t0mm0.common.net.

**Comment by versable** [comment]
Never mind, fixed

**Comment by Lynx187** [comment]
I think the 2nd header entry should be 'X-Requested-With' not just 'Requested'.

**Comment by versable** [comment]
You were right, mea culpa, Works now.

**Comment by versable** [comment]
Just a little update, use json for the source url request instead of regex, to make the code cleaner.

**Comment by versable** [comment]
Ready to be merged...

**Comment by Lynx187** [comment]
As I already mentioned, in the future I want to pass the parameters to the fuctions which are called via the xstream.py. Already adding this as (params) an optional argument to the relevant functions (these are the functions you set as next function for the GuiElement and so on), would be good.

More important: If you can't get the direct links to the hosters with the request for the hosterlist, then I prefer to get this link later. This can avoid unnecessary additional requests for the hosters. So, I would call __getSource() in getHosterUrl().

**Comment by versable** [comment]
Do you mean the function updateMeta(params) in xstream.py?

**Comment by Lynx187** [comment]
No I mean the "function" you set for a GuiElement for the next addon run. They're usually  called here https://github.com/Lynx187/plugin.video.xstream/blob/master/xstream.py#L196
"function()" will become "function(params)"
So, it would bei nice if you would change, e.g., "def load()" to "def load(params=False)" and so on.

**Comment by versable** [comment]
It's a bit clearer to me now. Would you push a commit where these changes are made to burning_series_org.py and I could follow suite for the pull requests? Eventually I could change the other site plugins if I find the time.

**Pull request merged**
