### PR TITLE
Add site hdfilme

### PR DESCRIPTION
**Pull request by versable**
I'd still like to get some additions to the code for this site in. Such as setting meta-data for season/episodes when a tv-show is loaded. Everything else works fine.

The sections top movies/tv-shows could also be added.

Greetings,

Mike

### CODE REVIEW

**Comment by versable** [comment]
Done, ready to merge if there isn't any objection

**Comment by Lynx187** [comment]
Did you test it? By looking through the code I would say that the part for immediately playing if there is only one link in `showLinks()` will not work. `showLinks()` is always set for GuiElements coming from `showEntries()`. But these are not added with `oGui.addFolder(oGuiElement, params, **False**)`. Without the `False` statement xStream will not process this via the stream functions, so the returned values/links will not be processed, too.

The rest is fine here comes only minor stuff:
If it is handling a movie (no episodes) and if there are multpile "hosterlinks" a new listing is created by `showLinks()` . That's not the default procedure for hosters. But in this case it is probably only for selecting the quality, so not a problem.

`showHosters()` is either showing Episodes (if its a season) or getting the hosterlinks via `showLinks()` (if its a movie). I think it is possible spilt this and set different functions for the previous GuiElement (line 76). For example, "showEpisodes" for seasons and "showLinks"/"showHosters" for movies.

**Comment by versable** [comment]
Again, you were right, the immediately play commit breaks the whole site plugin. I've removed it for now.

For the default procedure for hoster links, You are right, the links hosted on the site are hosted on google servers, and I couldn't get the default dialog (resolved set or not) to show in the default hoster dialog.

Tbh, I never written anything in python, the commits pushed here are in fact the first time I touched python. I am still learning the nuts and bolts of xStream, improving code when I feel it is overly convoluted. So be patient with me ;).

Separating the functions for tv-shows and movies makes sense, primarily for readability. So I will follow up on that.

Thanks for the feedback,

Mike

**Comment by Lynx187** [comment]
Hm right, currently the hosterlist, especially the filtering, does not really support hosters which are not in the urlresolver. At the moment you could just give a "wrong" hoster name of a suppoerted hoster. And for "displayedName" you set the name you really want to show. Link stays the correct.
For the User it will look pretty normal and due to the behaviour of "play" the correct stream should be started anyway.

**Comment by francescosoft** [comment]
Hello,

Any news on this ?

**Pull request merged**
